
select top 10 * from [dbo].[customer]

-- what is the total revenue generated by male and female customers
select gender, 
sum(purchase_amount_usd) as total_revenue
from [dbo].[customer]
group by gender
order by total_revenue desc

-- which customers used a discount but spent more than the average purchase amount
select customer_id, purchase_amount_usd 
from [dbo].[customer]
where discount_applied = 'Yes' and
purchase_amount_usd > (select AVG(purchase_amount_usd) from [dbo].[customer])

-- which are the top 5 products with the highest average of review rating
select top 5 item_purchased as products,
round(avg(review_rating),2) as avg_review_rating
from [dbo].[customer]
group by item_purchased
order by avg_review_rating desc

-- Compare average purchase amount between Standard & Express Shipping
select shipping_type,
ROUND(avg(purchase_amount_usd),2) as avg_purchase_amount
from [dbo].[customer] 
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg_purchase_amount desc

-- Do subscribed customers spend more. Compare average spend and total revenue 
-- between subscribers and non subscibers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(avg(purchase_amount_usd),2) as avg_spend,
round(sum(purchase_amount_usd),2) as total_revenue
from [dbo].[customer]
group by subscription_status
order by total_revenue, avg_spend desc

-- which 5 products have the highest percentage of purchases with discount applied.
select top 5 item_purchased as products,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT(*),2) 
as discount_rating 
from [dbo].[customer]
group by item_purchased
order by discount_rating desc

-- Segment customers into New, Returning, and Loyal based on their total number of
-- previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases <= 2 THEN 'New'
	WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from [dbo].[customer]
)

select customer_segment, count(*) as [Total Customers]
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within each category
with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY COUNT(customer_id) desc) as item_rank
from [dbo].[customer]
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe.
select subscription_status,
count(customer_id) as repeat_buyers
from [dbo].[customer]
where previous_purchases > 5
group by subscription_status

-- What is the revenue contribution of each age group.
select age_group, 
sum(purchase_amount_usd) as [Revenue Contribution]
from [dbo].[customer]
group by age_group
order by [Revenue Contribution] desc